<Columns>
    <px:PXGridColumn DataField="Selected" Type="CheckBox" Width="60"></px:PXGridColumn>
    <px:PXGridColumn DataField="Version" Width="70"></px:PXGridColumn>
    <px:PXGridColumn DataField="Name" Width="70"></px:PXGridColumn>
    <px:PXGridColumn DataField="ActionName" Width="70"></px:PXGridColumn>
    <px:PXGridColumn DataField="CreatedDateTime" Width="90"></px:PXGridColumn>
    <px:PXGridColumn DataField="LastModifiedByID" Width="90"></px:PXGridColumn>
</Columns>